### ISSUE TITLE
This file is not used anymore.

### ISSUE THREAD

**Issue by pelikhan** [sparkfun/pxt-gator-environment#2]
https://github.com/sparkfun/pxt-gator-environment/blob/d104678c404ac1b32458c69c888d4091802c85e7/shims.d.ts#L1

**Comment by AndyEngland521** [comment]
So can I just delete it and dump it from pxt.json?

**Comment by pelikhan** [comment]
Yup

________________________________

**Comment by AndyEngland521** [comment]
Right on, and I'm assuming I can do this for the rest of the packages?

**Comment by AndyEngland521** [comment]
So I've done this and I'm getting "error: please add 'shims.d.ts' to "files" in pxt.json"

**Comment by pelikhan** [comment]
Sorry my bad, you still have c++ here so you need to keep the file. Disregard!
