### ISSUE TITLE
Compatibility with micro:bit v2

### ISSUE THREAD

**Issue by microbit-sam** [sparkfun/pxt-gator-environment#3]
Hi @sparkfun,

As you might have seen from https://github.com/microsoft/pxt-microbit/issues/3506 this extension is currently not compiling against the latest version of Micro:bit CODAL. This means it will not work with micro:bit V2.

Software for micro:bit V2 boards is built using CODAL rather than the DAL, and no longer includes the mbed layer. We’ve implemented the most frequently used mbed classes to support easy porting of existing extensions, but there may still be corner cases with this compatibility layer. 

As your extension is currently not building, it will be disabled for micro:bit V2. People attempting to use your extension with a micro:bit V2 board will get error 929. This extension will only be re-enabled on micro:bit V2 once it is fixed.

There are details on how to ensure extensions work on both version of the micro:bit [here](https://github.com/lancaster-university/codal-microbit-v2/issues/31).

Looking at your extension source I believe that your extension falls under this category:

> 2. Use of mbed APIs that are not included in the compatibility layer, or microbit-dal APIs that need different constructors

We're currently looking into I2C compatibility, and any updates will be tracked on 

```
/home/build/prjclone/pxtapp/gatorEnvironment/SparkFunEnvironment.cpp:30:42: error: no matching function for call to 'codal::NRF52I2C::NRF52I2C(PinName, PinName)'
```

**Comment by loricrotser** [comment]
Hey @microbit-sam! I've just recently been assigned to these micro:bit issues, and after digging in a bit, I think I need some direction on the NRF52I2C support. Do you have a few minutes to reach out? I think it'll actually fix a few of the micro:bit extension issues we're seeing. Also cc'ing @finneyj. Thank you!

**Comment by MakeAndLearn** [comment]
Hi @loricrotser, how is it going? Do you think you'll be able to fix this problem?

**Comment by bsiever** [comment]
@loricrotser. I don't have a Gator Environment to test against, but here's a version that compiles: https://github.com/bsiever/pxt-gator-environment .  It needs to be tested on both V1 and V2 (changes impact both). 

Here's a test project that includes it: https://makecode.microbit.org/_Mu3fTfgLCRcx

If it works ok, I'll do a PR. 

(Edit/update:  I cleaned the code up a tiny bit.  Both repo and link were updated)

**Comment by finneyj** [comment]
Thanks for looking into these issues folks. @loricrotser please do ask away if you have any questions :)

**Comment by bsiever** [comment]
@loricrotser PR  #5  created!

**Comment by bsiever** [comment]
@loricrotser Hopefully you can close this issue now.

**Comment by microbit-mark** [comment]
Thanks for your work on this @bsiever. @loricrotser I think you may need to run another tagged release of the extension for the updated version https://github.com/sparkfun/pxt-gator-environment/blob/master/pxt.json#L3 to be picked up in MakeCode 

You can do this in https://github.com/sparkfun/pxt-gator-environment/tags

**Comment by loricrotser** [comment]
I think I just did this? GitHub is a new animal for me... lmk

**Comment by loricrotser** [comment]
Double checked by @bsiever. Closing issue
