### ISSUE TITLE
Not working with micro:bit v2.0

### ISSUE THREAD

**Issue by MakeAndLearn** [sparkfun/pxt-gator-environment#6]
We're testing the simplest program one can code with MakeCode and your extension "GatorEnvironment" using micro:bit v2 and we're getting the **error code "927"**. So looks like your extension's still not working with this version yet. We're trying the same program with the micro:bit v1 and works just fine. 

![microbit-screenshot](https://user-images.githubusercontent.com/58392278/204034300-829ba188-86e1-4201-beda-866d13b18cff.png)

Could you check it please? We work with many schools in Spain and they're finding this problem during their classes and we don't know how to solve it as we don't have enough microbits v1 for everyone.

Thanks!

**Comment by loricrotser** [comment]
micro:bit has updated to the latest version and approved.
